INSERT INTO USERS VALUES('car','scarvarez',true);
INSERT INTO USERS VALUES('admin','admin',true);
INSERT INTO USERS VALUES('mike','password',true);

INSERT INTO AUTHORITIES VALUES('car','ROLE_SCARVAREZ_MEMBER');
INSERT INTO AUTHORITIES VALUES('admin','ROLE_SCARVAREZ_MEMBER');
INSERT INTO AUTHORITIES VALUES('mike','ROLE_SCARVAREZ_MEMBER');

INSERT INTO GROUPS VALUES(1,'GROUP_MEMBERS_SCARV');
INSERT INTO GROUP_MEMBERS VALUES(1,'car');
INSERT INTO GROUP_MEMBERS VALUES(1,'admin');
--INSERT INTO GROUP_MEMBERS VALUES(1,'mike');
INSERT INTO GROUP_AUTHORITIES VALUES(1,'ROLE_SCARVAREZ_MEMBER');

COMMIT;